# Sistem persamaan 10 variabel 

In [70]:
import numpy as np

# Terdapat 2 contoh
# 1. 3 variabel
         5x1  - 2x2 + 3x3 = -1
        -3x1 + 9x2 + 1x3 = 2
         2x1  - 1x2  - 7x3 = 3

# 2. 10 Variabel
         5x1 + 6x2  -8x3  -3x4 + 1x5 + 5x6 + 9x7  -2x8  -3x9 + 7x10 = 23
         -2x1 + 3x2 + 9x3 + 9x4  -3x5 + 6x6 + 1x7 + 9x8 + 7x9  -3x10 = 11
         5x1  -7x2 + 2x3 + 8x4 + 5x5 + 9x6  -1x7  -5x8  -7x9 + 4x10 = 82
         6x1 + 4x2 + 7x3  -1x4  -7x5 + 9x6  -2x7 + 5x8 + 7x9  -9x10 = 14
         1x1 + 5x2 + 8x3  -3x4 + 8x5 + 2x6  -3x7 + 2x8  -4x9 + 6x10 = 74
         -2x1 + 5x2 + 6x3 + 9x4  -4x5 + 2x6 + 7x7 + 2x8  -5x9 + 1x10 = 23
         9x1 + 4x2  -1x3  -5x4 + 7x5 + 2x6  -5x7 + 8x8  -2x9  -6x10 = 67
         4x1 + 5x2 + 7x3  -8x4  -1x5 + 1x6 + 2x7 + 4x8 + 1x9  -6x10 = 12
         3x1 + 6x2  -9x3 + 1x4 + 4x5 + 7x6  -2x7 + 6x8 + 1x9  -5x10 = 47
         6x1  -3x2 + 6x3 + 8x4 + 2x5  -4x6 + 7x7 + 9x8  -2x9 + 5x10 = 37

## 1. Eliminasi gauss

In [71]:
a = np.array([[5,-2,3],
             [-3,9,1],
             [2,-1,-7]])
b = np.array([-1,2,3])
n = len(a[1])

idx = 0
while idx<n:
    eqline = ""
    idy = 1
    for coef in a[idx]:
        varx = 'x' +str(idy)
        tanda = '+'
        if coef<0 or idy<2 : tanda = ''
        eqline +=tanda+' '+str(coef)+varx+' '
        idy +=1
    eqline +='= '+str(b[idx])
    print(eqline)
    idx +=1
#___forward elimination
k = 0
while k<(n-1):
    i = k+1
    while i<n:
        faktor=a[i][k]/a[k][k]
        j = k+1
        a[i][k]=0
        while j<n:
            a[i][j] -= faktor*a[k][j]
            j+=1
        b[i] -= faktor*b[k]
        i +=1
    k+=1
print("\nMatriks A =")
print(a)
print("Matriks B =")
print(b)

x = []
y = 0
while y<n:
    x.append(0)
    y+=1
    
#___back substitution
x[n-1] = b[n-1]/a[n-1][n-1]
i = n-2
while i>=0:
    jumlah = 0
    j = i+1
    while j<n:
        jumlah += a[i][j]*x[j]
        j += 1
    x[i] = (b[i]-jumlah)/a[i][i]
    i -= 1

print("\nhasil")
idx = 0
while idx<n:
    idy = 'x'+str(idx+1)
    print(idy,'=',x[idx])
    idx += 1


 5x1  -2x2 + 3x3 = -1
 -3x1 + 9x2 + 1x3 = 2
 2x1  -1x2  -7x3 = 3

Matriks A =
[[ 5 -2  3]
 [ 0  7  2]
 [ 0  0 -8]]
Matriks B =
[-1  1  3]

hasil
x1 = 0.125
x2 = 0.25
x3 = -0.375


In [72]:
a = np.array([[5,6,-8,-3,1,5,9,-2,-3,7],
     [-2,3,9,9,-3,6,1,9,7,-3],
     [5,-7,2,8,5,9,-1,-5,-7,4],
     [6,4,7,-1,-7,9,-2,5,7,-9],
     [1,5,8,-3,8,2,-3,2,-4,6],
     [-2,5,6,9,-4,2,7,2,-5,1],
     [9,4,-1,-5,7,2,-5,8,-2,-6],
     [4,5,7,-8,-1,1,2,4,1,-6],
     [3,6,-9,1,4,7,-2,6,1,-5],
     [6,-3,6,8,2,-4,7,9,-2,5]])
b =  np.array([23,11,82,14,74,23,67,12,47,37])
n = len(a[1])

idx = 0
while idx<n:
    eqline = ""
    idy = 1
    for coef in a[idx]:
        varx = 'x' +str(idy)
        tanda = '+'
        if coef<0 or idy<2 : tanda = ''
        eqline +=tanda+' '+str(coef)+varx+' '
        idy +=1
    eqline +='= '+str(b[idx])
    print(eqline)
    idx +=1
#___forward elimination
k = 0
while k<(n-1):
    i = k+1
    while i<n:
        faktor=a[i][k]/a[k][k]
        j = k+1
        a[i][k]=0
        while j<n:
            a[i][j] -= faktor*a[k][j]
            j+=1
        b[i] -= faktor*b[k]
        i +=1
    k+=1
print("\nMatriks A =")
print(a)
print("Matriks B =")
print(b)

x = []
y = 0
while y<n:
    x.append(0)
    y+=1
    
#___back substitution
x[n-1] = b[n-1]/a[n-1][n-1]
i = n-2
while i>=0:
    jumlah = 0
    j = i+1
    while j<n:
        jumlah += a[i][j]*x[j]
        j += 1
    x[i] = (b[i]-jumlah)/a[i][i]
    i -= 1

print("\nhasil")
idx = 0
while idx<n:
    idy = 'x'+str(idx+1)
    print(idy,'=',x[idx])
    idx += 1

 5x1 + 6x2  -8x3  -3x4 + 1x5 + 5x6 + 9x7  -2x8  -3x9 + 7x10 = 23
 -2x1 + 3x2 + 9x3 + 9x4  -3x5 + 6x6 + 1x7 + 9x8 + 7x9  -3x10 = 11
 5x1  -7x2 + 2x3 + 8x4 + 5x5 + 9x6  -1x7  -5x8  -7x9 + 4x10 = 82
 6x1 + 4x2 + 7x3  -1x4  -7x5 + 9x6  -2x7 + 5x8 + 7x9  -9x10 = 14
 1x1 + 5x2 + 8x3  -3x4 + 8x5 + 2x6  -3x7 + 2x8  -4x9 + 6x10 = 74
 -2x1 + 5x2 + 6x3 + 9x4  -4x5 + 2x6 + 7x7 + 2x8  -5x9 + 1x10 = 23
 9x1 + 4x2  -1x3  -5x4 + 7x5 + 2x6  -5x7 + 8x8  -2x9  -6x10 = 67
 4x1 + 5x2 + 7x3  -8x4  -1x5 + 1x6 + 2x7 + 4x8 + 1x9  -6x10 = 12
 3x1 + 6x2  -9x3 + 1x4 + 4x5 + 7x6  -2x7 + 6x8 + 1x9  -5x10 = 47
 6x1  -3x2 + 6x3 + 8x4 + 2x5  -4x6 + 7x7 + 9x8  -2x9 + 5x10 = 37

Matriks A =
[[  5   6  -8  -3   1   5   9  -2  -3   7]
 [  0   5   5   7  -2   8   4   8   5   0]
 [  0   0  23  29  -1  24   0  17   9  -3]
 [  0   0   0 -17  -8 -12  -9  -3   5 -14]
 [  0   0   0   0  14   0   0  -3 -11  14]
 [  0   0   0   0   0  -3   1  -6  -9   0]
 [  0   0   0   0   0   0 -10  20  22 -11]
 [  0   0   0   0   0   0   0  13 